## docker-compose down --rmi all
#  docker-compose build --no-cache
#  docker-compose up
# docker compose up --build
#docker-compose up -d --build pnr-service
#  docker-compose down -v
# Clean, build the jar, and force docker to ignore the cache
#  ./mvnw clean package -DskipTests
#  docker-compose up --build --force-recreate

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=pnrdb
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  pnr-service:
    build: .
    image: airline-pnr-service:latest
    container_name: pnr-service
    environment:
      - MONGO_USER=${DB_USER}
      - MONGO_PASS=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      mongodb :
        condition: service_healthy
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:       # localhost:3000, user/pass: admin/admin
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
