management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics ,threaddump
  metrics:
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: pnr-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo-db:27017/pnrdb?authSource=admin
#       uri: mongodb://hend:secret@localhost:27017/pnrdb?authSource=admin


  jackson:
    default-property-inclusion=non_absent:
    springdoc:
  swagger-ui:
    url: /openapi/pnr-spec.yml
    path: /swagger-ui.html

  logging:
  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger - %msg%n"
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate=DEBUG:


    com:
      airline:
        pnr: DEBUG


